project_id = "mcopjnrsysvszczixskd"

[functions.ai-search]
verify_jwt = true

[functions.ai-recommendations]  
verify_jwt = true

[functions.ai-property-assistant]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false